# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f0335994d068af7173b53c6bb0b6f05edec12a8caa5f7b4966f44e1813f66097455032dcdba84926888b28e99b803980d04558daa5c0ea1f46cfffb60d9995f

test:
  secret_key_base: 1ce8732ac84d3a108199335081fbf3b535f7036ec5d3935ac5ec41b9e4859466300d9d7d5f78eb88f511d3e0192a3feded3bed45c07a0944d1534d319ef22dd0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
